### PR TITLE
Fix bugs: class no found for servlet; no applications, services... menu entries; no log output. enhance script start.sh

### PR DESCRIPTION
**Pull request by huadong**
#3 
Fix bugs: 
1. class no found for servlet; 
2. no applications, services... menu entries; 
3. no log output. 

Enhance start script:
enhance script start.sh

### CODE REVIEW

**Comment by huanzhang** [comment]
@huadong 多谢！

另外，作为提醒：要是只fix没有applications和services目录，改下配置文件就可以了

**Comment by kingyoungfan** [comment]
我使用最新版的dubbo，monitor中心后台还是没有 Applications, Services, Hosts 菜单入口，怎么解决？

**Comment by jiaopy** [comment]
jetty-monitor=com.alibaba.dubbo.monitor.simple.container.JettyContainer

dubbo.container=log4j,spring,registry,jetty-monitor
这样改就好了

**Comment by htynkn** [comment]
this PR looks good to me.
I have a little concern about including `slf4j-log4j12` as a dependency, user should able to have more choice. but we can discuss this later.

**Comment by htynkn** [comment]
Run `mvn clean package`, all pass.

**Pull request merged**
