### PR TITLE
upgrade jdk5 to jdk6+

### PR DESCRIPTION
**Pull request by zonghaishang**
upgrade default jdk5 to jdk6+, refer from:

https://github.com/apache/incubator-dubbo-ops/issues/17

### CODE REVIEW

**Comment by ralf0131** [comment]
Hello, can you resolve the conflicts here? In this way you also trigger a UT check.

**Comment by zonghaishang** [comment]
done

**Comment by ralf0131** [comment]
Suddenly I've realized that Dubbo ops now runs on Java 8, is it pull request still valid?

**Comment by diecui1202** [comment]
Now it's based on spring boot2. So I think this PR need to close.

**Pull request closed without merging**
